
version: '3.5'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig
      - MYSQL_USER=ROOT
      - MYSQL_USER_PASSWORD=ppassword
    depends_on:
      - db 
  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server